---
title: "Installing R and RStudio"
date: "Last updated: `r Sys.Date()`"
output: 
  html_document:
    theme: cosmo
    toc: true
    toc_depth: 3
    toc_float:
      collapsed: false
      smooth_scroll: true
---

R is the programming language that you use when working with data.
RStudio is a development environment that makes working with R much more convenient.
Both are free to download and install.

To download R, go to [cloud.r-project.org](https://cloud.r-project.org/) and follow the instructions on the page.
To download RStudio, go to [rstudio.com/products/rstudio/download](https://www.rstudio.com/products/rstudio/download/), scroll down and download the file recommended for your operating system.

When installing, you can always stick to the default settings, unless you have different preferences.

In case you get stuck at any point, or would like more guidance in the installation process, feel free to check out any of the following links:

* [Tutorial: Getting Started with R and RStudio](https://www.dataquest.io/blog/tutorial-getting-started-with-r-and-rstudio/)
* [R Tutorial: How to install R and R studio (video)](https://www.youtube.com/watch?v=0Qu7Jg1Jw5A)