---
title: "SCIENVI303<br>Topics in Ecology<br>Spring 2023"
date: 'Last updated: `r Sys.Date()`'
output:
  html_document:
    theme: cosmo
    toc: yes
    toc_depth: 3
    toc_float:
      collapsed: no
      smooth_scroll: yes
---

\

# Introduction

This page collects workshop materials, data sources and supplementary materials for the data-driven assignments in the Spring 2023 edition of Ecology at UCR.
You can also access the related files directly on [Github](https://github.com/ucrdatacenter/projects/tree/main/SCIENVI201/2022h1).

If you have any questions related to the assignment do not hesitate to reach Jennifer or Bianka during Data Center office hours (tbh). There is no need to sign up in advance to join office hours. If this time is inconvenient for you feel free to write Jennifer or Bianka an email (ucrdatacenter@ucr.nl) to schedule an individual meeting. 

\

# Working with R and RStudio

## Recommended reading

It is highly recommended that you read the sections 2, 3.1-3.4 and 4-6 of [A (very) short introduction to R](https://github.com/ClaudiaBrauer/A-very-short-introduction-to-R/blob/master/documents/A\%20(very)\%20short\%20introduction\%20to\%20R.pdf) and sections 1-4 of [How to make any plot in ggplot2?](http://r-statistics.co/ggplot2-Tutorial-With-R.html#6.1\%20Make\%20a\%20time\%20series\%20plot\%20(using\%20ggfortify)) before starting working with R. 

## Installing R and RStudio

R is the programming language that you use when working with data.
RStudio is a development environment that makes working with R much more convenient.
Both are free to download and install.

To download R, go to [cloud.r-project.org](https://cloud.r-project.org/) and follow the instructions on the page.
To download RStudio, go to [rstudio.com/products/rstudio/download](https://www.rstudio.com/products/rstudio/download/), scroll down and download the file recommended for your operating system.

When installing, you can always stick to the default settings, unless you have different preferences.

In case you get stuck at any point, or would like more guidance in the installation process, feel free to check out any of the following links:

* [Tutorial: Getting Started with R and RStudio](https://www.dataquest.io/blog/tutorial-getting-started-with-r-and-rstudio/)
* [R Tutorial: How to install R and R studio (video)](https://www.youtube.com/watch?v=0Qu7Jg1Jw5A)
       
## Creating a project in RStudio

It is convenient to create an R project for an assignment that you are working on.
A project is basically a folder that stores all files related to the assignment.

You can create a project as follows:

* Open RStudio and click on "Project: (None)" in the top right corner.
* Open the dropdown window and click on "New Project...."
* In the popup window select "New Directory", then "New Project."
* Choose a sensible name for your project and enter it as the Directory Name. You can either use the default file path or change it by clicking "Browse..." next to "Create project as a subdirectory of:."
* Finally, click on "Create project."

After a project is created, there are two easy ways of accessing it. 
You can either use the same dropdown window in the top right corner of RStudio that you used to create the project, and click on the name of the project there, or you can find the project folder within your files and click on the file with the .Rproj extension.

\

# Simple Assignment

The simple assignment is an initial workshop in R where you follow the instructions and codes given to you on the website to get yourself familiar with R. This assignment is compulsory, therefore, everyone has to complete it. The instructions for the simple assignment can be found [here](SCIENVI303/SmallAssignment.html).

# Research Assignment
