---
title: "SSCECON209<br>Money, Banking and Finance<br>Spring 2022"
date: "Last updated: `r Sys.Date()`"
output: 
  html_document:
    theme: cosmo
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: true
---

# Introduction

This page collects helpful links for the banking dashboard assignment in the Spring 2022 edition of Money, Banking and Finance.

If you have questions related to the dashboard assignment or need some help, feel free to join Data Center office hours with Tina (held every Wednesday between 15:00-17:00 on [Zoom](https://universitycollegeroosevelt.zoom.us/j/5393037767?pwd=d1FxZFN1UDVqZUsrU204R1gzQWF4Zz09)). 
You don't need to sing up in advance to attend office hours.
Additionally, feel free to email Tina (t.rozsos@ucr.nl) to schedule an individual consultation outside of office hours.

# Example dashboard

You can download a basic example of a banking dashboard by clicking [here](https://github.com/ucrdatacenter/projects/raw/main/SSCECON209/2022h1/example%20dashboard.xlsx).

# Helpful links

## Excel basics

* [Excel cheat sheet](https://www.customguide.com/cheat-sheet/excel-cheat-sheet.pdf)
* [List of most important formulas](https://web.acd.ccac.edu/~ndowney/CIT140/Excel/Formulas.pdf)
* [Full tutorial from opening Excel to making charts (video)](https://www.youtube.com/watch?v=e7xGuGqgp-Q)
* [Cell referencing (video)](https://www.youtube.com/watch?v=Yx52CYvR5ao)
* [Working with multiple sheets (video)](https://www.youtube.com/watch?v=4HdZx29SdoM)
* [Excel Formulas and Functions Tutorial (video)](https://www.youtube.com/watch?v=Jl0Qk63z2ZY)

## Making figures in Excel

* [Creating a chart step-by-step](https://www.excel-easy.com/data-analysis/charts.html)
* [Creating a simple line chart (video)](https://www.youtube.com/watch?v=3o11OlLgYDo)
* [Plotting multiple lines on one chart (video)](https://www.youtube.com/watch?v=YhmVVRwj3p8)
* [Creating a scatterplot (video)](https://www.youtube.com/watch?v=OVA2M7EIx80)
* [Customizing charts (video)](https://www.youtube.com/watch?v=TfkNkrKMF5c)
