---
layout: page
title: "SCIBIOM303<br> Mechanisms of Disease"
subtitle: "Spring 2025"
date: "Last updated: `r Sys.Date()`"
output:
  md_document:
    variant: gfm
    preserve_yaml: true
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE, error=FALSE)
```

# Introduction

This page collects materials for the data-driven assignments in the Spring 2025 edition of Mechanisms of Disease at UCR.
You can also access the related files (data and R scripts) directly on [GitHub](https://github.com/ucrdatacenter/projects/tree/main/SCIBIOM303/2025h1).

# Office hours

The Data Center offers office hours to help you with the data-driven assignments.
You can find more information about the schedule [here](../../contact).

# Preparation for Data Center workshops

To participate in the workshops, you will need to have R and RStudio installed on your computer. 
If you don’t have these programs installed, please follow [this installation tutorial](../../tutorials/r_install).

In addition the [R basics tutorial](../../../tutorials/r_basics) on the  Data Center website explains the RStudio interface, and shows how to create a new project and how to install packages.

# Workshop materials

**To be added.**